version: '3.7'

services:
  iperform-server:
    image: iperform-server:latest
    env_file:
      - .env
    ports:
      - 8188:8184
  iperform-database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1412
      - POSTGRES_DB=mydb
    volumes:
      - D:\ikame\Java\iperform\src\main\resources\schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432