server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=iperform&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: 1412
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:schema.sql
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: especiallygamesbdd@gmail.com
    password: wiwvcqsubgnrzrwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

slack-config:
  user-oauth-token: xoxp-4127893326450-5988206214897-6437066513942-0286375069f1a4e26befcd47b9bb33e4
  bot-user-oauth-token: xoxb-4127893326450-6417062971715-la4ZROJhnMATU08h27AHPdGB
